### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by Jo-KLS** [bkernal626/Service-Scope#10]
Can we change how quickly I am automatically signed out? 
At this point I am in and out of the lists all day long, but it keeps signing me out.
This is becoming irritating.
Can we change it to 2 hours before it signs me out?

Thanks,
Jo

**Comment by bkernal626** [comment]
Do you use Google Chrome?

**Comment by bkernal626** [comment]
I will look into adding the ability of autofilling the login, because it is a security implementation that I do not want to remove, otherwise I can change it to something like 2 hours temporarily until more people start using it

**Comment by Jo-KLS** [comment]
Ok, so the timeout timer is system wide and can't be changed per account, correct?


Auto-login would be helpful, but it won't open back up to the page I was on, will it?




Jo Dykes

Kern Lawn Service

651-207-5396


________________________________

**Comment by bkernal626** [comment]
Correct, it can't be per account.
It won't go back to the same page, but i will look into the code necessary to autofill the login when i get a chance. Temporarily I will increase the timeout amount to 2 hours

**Comment by bkernal626** [comment]
I'll look into this again, and yeah the keep me logged in button does not work right now, but I can add that functionality this weekend

**Comment by Jo-KLS** [comment]
Thank you.

My temporary solution is to pile everything up and then log in and enter it.

I prefer to enter it as it comes in rather than wasting the paper to print it all for later.



Jo Dykes

Kern Lawn Service, Inc.

915 N Albert St

St Paul, MN 55104

651-207-5396


________________________________

**Comment by bkernal626** [comment]
Inactive timeout is now 45 min and keep me logged in will keep you logged in for 12 hours
