### ISSUE TITLE
Cents

### ISSUE THREAD

**Issue by Jo-KLS** [bkernal626/Service-Scope#15]
Can you make it so when I create a number column it will hold 2 places to the right of a decimal point?
I typically use that column for entering the customers cost. It is rare that we have any with cents, but I have a few now that do. For example: $360.25. I currently have to enter the amount in the notes section. The cost column will hold the $360, but not the .25.  This is not urgent.

**Comment by bkernal626** [comment]
You should be able to do this already. I made this update a month or two ago after realizing this. You should be able to add as many decimal places as you would like. Let me know an example if its not working as expected so I can look into that specific issue.

**Comment by Jo-KLS** [comment]
Sweet. It works.

Hadn't tried to enter change since November.


Jo Dykes

Kern Lawn Service, Inc.

915 N Albert St

St Paul, MN 55104

651-207-5396


________________________________
