### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by Jo-KLS** [bkernal626/Service-Scope#6]
My e-mail still isn't verified. I know I was waiting on something for this, but I don't remember what. Sorry.  What should I do on this?

**Comment by bkernal626** [comment]
You should be able to go to the Profile page and click 'Verify Email for Sending.' Follow the instructions, and this will verify your email for use to send emails directly from the website.

**Comment by Jo-KLS** [comment]
We can now verify our emails.

Mine has been verified.


Jo Dykes

Kern Lawn Service

651-207-5396


________________________________
