### ISSUE TITLE
Multiple customer emails

### ISSUE THREAD

**Issue by Jo-KLS** [bkernal626/Service-Scope#7]
I have many customers that have more than 1 email that messages need to be sent to, but the system won't allow me to enter more than 1 email. Is there a trick to it?

**Comment by bkernal626** [comment]
Currently it does not support this. I can add it over the weekend as a new feature.

**Comment by Jo-KLS** [comment]
Thank you


Jo Dykes

Kern Lawn Service

651-207-5396

________________________________

**Comment by Jo-KLS** [comment]
None of the issues I am sending you are urgent.

I am just starting to enter info and letting you know what issues I find as I find them.


Jo Dykes

Kern Lawn Service

651-207-5396

________________________________

**Comment by bkernal626** [comment]
You are now able to add multiple emails from the Details page. This will send to all of those emails when choosing that customer in the selected recipients for a Send Email request.
