### ISSUE TITLE
Master list services

### ISSUE THREAD

**Issue by Jo-KLS** [bkernal626/Service-Scope#9]
Is there a way to modify the master customer list so that it shows all customer lists that they are on?
Specifically when I download the csv?
For example if 1053 cromwell is signed up for mowing and gutters on the csv file it would show their price in those columns. At the very least if it could list mowing and gutters next to their name so that I know they are signed up for those services.

Thanks,
Jo

**Comment by bkernal626** [comment]
I can look into adding that functionality when downloading. Would it be okay to do a comma separated list of all the lists that customer is in as its own column in the master list when downloading?

**Comment by Jo-KLS** [comment]
I think that would work.



Jo Dykes

Kern Lawn Service

651-207-5396

________________________________

**Comment by Jo-KLS** [comment]
John says this needs to be top priority.


Jo Dykes

Kern Lawn Service

651-207-5396

________________________________

**Comment by bkernal626** [comment]
I will most likely be able to complete it this weekend.

Another option you can do if its urgent is create another list with headers as the other lists and just check the lists they are on so then you are able to export that.

For example 
<img width="1416" alt="screen shot 2018-05-04 at 11 04 12 am" src="https://user-images.githubusercontent.com/22935336/39638190-08b972ac-4f8b-11e8-8fa8-fd8600ea048e.png">

And you just make sure they match the selected lists in the customer details page.

**Comment by Jo-KLS** [comment]
It is 464 customers and like 10 lists.

It would take days!


If there is no other way then I guess I will have to, but lets explore every other option first.


I was able to get John a list of customers that aren't on the list to work with in the meantime.


Jo Dykes

Kern Lawn Service

651-207-5396

________________________________

**Comment by bkernal626** [comment]
I've added a column to display current lists they are on. This will be optimized in the export eventually so it's easier to sort, but I hope it will do for now.

**Comment by Jo-KLS** [comment]
Yes, this will work for now.

Eventually being able to sort by service will be very helpful.


Thank you,


Jo Dykes

Kern Lawn Service

651-207-5396

________________________________

**Comment by bkernal626** [comment]
Added customer lists to export
